#!/bin/bash
#
# Squish a CM otapackage for distribution
# cyanogen
#

. $ANDROID_BUILD_TOP/device/samsung/p3/releasetools/functions

if [ -z `uname -a | grep Darwin` ]
then
   # Linux
   XARGS="xargs --max-args=1 --max-procs `grep 'processor' /proc/cpuinfo|wc -l`"
else
   # Darwin
   XARGS="xargs -n 1 -P `sysctl hw.ncpu | awk '{print $2}'`"
fi

if [ -z "$OUT" -o ! -d "$OUT" ]; then
	echo -e $CL_RED"ERROR: $0 only works with a full build environment. $OUT should exist."$CL_RST
	exit 1
fi

if [ ! -f "$OTAPACKAGE" ]; then
	echo -e $CL_RED"$OTAPACKAGE doesn't exist!"$CL_RST;
	exit 1
fi

OPTICHARGER=$ANDROID_BUILD_TOP/device/samsung/p3/releasetools/opticharger
QUIET=-q
REPACK=$OUT/repack.d
if [ -d $REPACK ]; then
	printf "Sanitizing environment..."
	rm -rf $REPACK
	echo
fi

# Unpack the otapackage and opticharge all apks
mkdir -p $REPACK/ota
(
cd $REPACK/ota
printf "Unpacking $OTAPACKAGE..."
unzip $QUIET $OTAPACKAGE
echo

# Move all apks to the same directory so xargs can
# use also with framework-res.apk. This allow process
# framework-res.apk in parallel with other apks
mkdir -p $REPACK/parallel
cd $REPACK/parallel
cp $REPACK/ota/system/framework/framework-res.apk .
cp $REPACK/ota/system/app/*.apk .

# Do optimization in parallel
find ./ -name \*.apk | $XARGS $OPTICHARGER

# Move optimized apks to repack directory
mv -f $REPACK/parallel/framework-res.apk $REPACK/ota/system/framework/framework-res.apk
mv -f $REPACK/parallel/*.apk $REPACK/ota/system/app/

# Return to directory
cd $REPACK/ota
rm -rf $REPACK/parallel
)

# Include device specific script
if [ "$TARGET_PRODUCT" = "cm_p3" ]; then
        . $ANDROID_BUILD_TOP/device/samsung/p3/releasetools/squisher.sh
fi

# Pack it up
printf "Zipping package..."
( cd $REPACK/ota; zip $QUIET -r $REPACK/update.zip .; mv -f $REPACK/update.zip $OTAPACKAGE )
echo
printf "Cleaning up..."
rm -rf $REPACK
echo

exit 0
