# This script is included in squisher
# It is the final build step (after OTA package)

# Delete unwanted apps
rm -f $REPACK/ota/system/app/Calendar.apk
rm -f $REPACK/ota/system/app/CMWallpapers.apk
rm -f $REPACK/ota/system/app/QuickSearchBox.apk
rm -f $REPACK/ota/system/app/VideoEditor.apk
rm -f $REPACK/ota/system/bin/recovery
rm -f $REPACK/ota/system/lib/libvideoeditor_core.so
rm -f $REPACK/ota/system/lib/libvideoeditor_jni.so
rm -f $REPACK/ota/system/lib/libvideoeditor_osal.so
rm -f $REPACK/ota/system/lib/libvideoeditorplayer.so
rm -f $REPACK/ota/system/lib/libvideoeditor_videofilters.so
rm -f $REPACK/ota/system/media/audio/alarms/Curium.ogg
rm -f $REPACK/ota/system/media/audio/alarms/Fermium.ogg
rm -f $REPACK/ota/system/media/audio/alarms/Neptunium.ogg
rm -f $REPACK/ota/system/media/audio/alarms/Nobelium.ogg
rm -f $REPACK/ota/system/media/audio/alarms/Plutonium.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Adara.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Altair.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Antares.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Antimony.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Argon.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Beryllium.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Betelgeuse.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Canopus.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Capella.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Castor.ogg
rm -f $REPACK/ota/system/media/audio/notifications/CetiAlpha.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Cobalt.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Doink.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Electra.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Fluorine.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Fomalhaut.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Gallium.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Hojus.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Iridium.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Krypton.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Lalande.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Merope.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Mira.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Naughty.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Palladium.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Polaris.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Pollux.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Pong.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Procyon.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Proxima.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Radon.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Rang.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Regulus.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Rubidium.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Selenium.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Shaula.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Sirius.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Sirrah.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Stone.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Strontium.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Tejat.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Thallium.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Upsilon.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Vega.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Xenon.ogg
rm -f $REPACK/ota/system/media/audio/notifications/Zirconium.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Acheron.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/ArgoNavis.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Bongo.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Bootes.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Boxbeat.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/CanisMajor.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Cassiopeia.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Centaurus.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Cygnus.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Draco.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Eridani.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Gigolo.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Girtab.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/House_of_house.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Iridium.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Lyra.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Machina.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Nasqueron.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Pegasus.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Perseus.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Rigel.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Scarabaeus.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Sceptrum.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Silmarillia.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Solarium.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Testudo.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Themos.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/UrsaMinor.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Vespa.ogg
rm -f $REPACK/ota/system/media/audio/ringtones/Zeta.ogg
rm -f $REPACK/ota/system/tts/lang_pico/de-DE_gl0_sg.bin
rm -f $REPACK/ota/system/tts/lang_pico/de-DE_ta.bin
rm -f $REPACK/ota/system/tts/lang_pico/en-GB_kh0_sg.bin
rm -f $REPACK/ota/system/tts/lang_pico/en-GB_ta.bin
rm -f $REPACK/ota/system/tts/lang_pico/es-ES_ta.bin
rm -f $REPACK/ota/system/tts/lang_pico/es-ES_zl0_sg.bin
rm -f $REPACK/ota/system/tts/lang_pico/fr-FR_nk0_sg.bin
rm -f $REPACK/ota/system/tts/lang_pico/fr-FR_ta.bin
rm -f $REPACK/ota/system/tts/lang_pico/it-IT_cm0_sg.bin
rm -f $REPACK/ota/system/tts/lang_pico/it-IT_ta.bin
rm -f $REPACK/ota/system/xbin/rsync
rm -f $REPACK/ota/system/xbin/vim
rm -rf $REPACK/ota/system/usr/share/vim
